LinumLabs/psydao-io

components/token-container.tsx
components/windows/swap-widget.tsx
public/windows/swap/arrow-swap-icon.svg

added max button to swap widget

Feat: add max button

---

components/connect-button.tsx
components/linear-button.tsx
components/menu.tsx
components/modals/TsAndCs.tsx
components/swap-widget/SwapTsAndCs.tsx
components/windows/swap-widget.tsx

feat: terms and conditions

---

components/connect-button.tsx

smol fix to improve pop-up positioning on mobile

fix: improve pop-ups on mobile

---

components/token-container.tsx
components/windows/swap-widget.tsx
constants/ethMaxValueWithGas.ts

Refactor based on client requirements

feat: refactor and destructure

---

components/nft-sale-widget/layout/nft-sale/mint-section.tsx
components/nft-sale-widget/psyc-item.tsx
hooks/useBuyNft.ts
services/graph.ts

wip: refetch copy balance after minting

feat: show copy balance

---

components/nft-sale-widget/commons/connect-wallet-modal.tsx
components/nft-sale-widget/psyc-item.tsx

Feat: change wallet connect prompt to modal

---

components/admin-dashboard/admin-sales-section.tsx
components/commons/submit-button-container.tsx
components/commons/submit-sale-button.tsx
components/general-dashboard/save-settings-button.tsx

Fix: improve submit button container

---

components/admin-dashboard/admin-sale-component.tsx
components/admin-dashboard/admin-sales-section.tsx
components/nft-sale-widget/commons/connect-wallet-modal.tsx
components/nft-sale-widget/commons/sales-dropdown.tsx
components/nft-sale-widget/index.tsx
components/nft-sale-widget/layout/nft-sale-widget-empty.tsx
components/nft-sale-widget/layout/nft-sale/mint-psyc-header.tsx
components/nft-sale-widget/layout/nft-sale/mint-section.tsx
components/nft-sale-widget/layout/nft-sale/psyc-sale-content.tsx
components/nft-sale-widget/psyc-item.tsx
hooks/useEditSaleForm.tsx
hooks/useFetchProof.ts
hooks/useGetAddresses.tsx
hooks/useGetOnlyWhitelistedSales.tsx
lib/server-utils.ts
pages/index.tsx

test dropdown with only whitelisted sales

---

abis/coreAbiSepolia.json
constants/contracts.ts

NOTE: the core ABI only changed because I missed it earlier
no new ABI changes resulted from this redeployment

chore: update contract addresses and core abi

---

components/nft-sale-widget/index.tsx

Creating hot fix for proper user flow. This needs to be fixed ASAP when devs are back online

Hot Fix: enabling data flow

---

components/nft-sale-widget/index.tsx

Displaying sale widget as default

feat: displaying sale widget  as default

---

components/windows/swap-widget.tsx
services/web3/useWithdrawTokens.tsx

For testing only, please do not merge

TEST: Token withdrawals on Sepolia

---

components/nft-sale-widget/layout/owned-nfts/owned-nfts.tsx
services/graph.ts

- fix for wrong images being displayed in the owned tab

fix for owned psyc image

---

components/edit-sale-window/index.tsx
components/nft-sale-widget/index.tsx
components/nft-sale-widget/layout/owned-nfts/owned-nfts.tsx
components/ui/token-container.tsx
hooks/useBuyNft.ts
hooks/useCreateSale.ts
hooks/useCustomToasts.ts
hooks/useEditSaleForm.tsx
hooks/useFetchTokenOwner.ts
hooks/useGeneralSettingsForm.ts
hooks/useGetCurrentSaleValues.tsx
hooks/useRandomImage.ts
hooks/useSaveGeneralSettings.ts
hooks/useTokenIds.ts
hooks/useUpdateRevenueSplits.ts
hooks/useWithdrawRoyalties.ts
services/generateNftIds.ts
utils/transactionHandlers.ts

- removed console.logs
- removed some unused imports

removing console.logs

---

components/ui/head.tsx

feat: update link preview text

---

components/nft-sale-widget/commons/skeleton-card.tsx
components/nft-sale-widget/index.tsx
components/nft-sale-widget/layout/nft-sale/mint-section.tsx
components/nft-sale-widget/layout/nft-sale/psyc-sale-content.tsx
components/nft-sale-widget/layout/owned-nfts/owned-nfts-section.tsx
components/nft-sale-widget/layout/owned-nfts/owned-nfts.tsx
components/nft-sale-widget/psyc-item.tsx

- added a fallback skeleton loader for when images are not fully loaded
- optimized image component loading states

hotfix skeleton loader for psy images

---

hooks/useUserCopyBalances.ts

- fix for the userCopyBalances refetch bug

balances refetch fix

---

components/nft-sale-widget/commons/mint-button-comp.tsx
components/nft-sale-widget/layout/nft-sale/mint-section.tsx
components/nft-sale-widget/layout/owned-nfts/owned-nfts.tsx
components/nft-sale-widget/psyc-item.tsx
hooks/useBatchSoldOut.ts
hooks/useUserCopyBalances.ts

- added a hook to manage the sold out state for the batch
- fixed sold-out state update issue

fix for sold-out state update

---

components/nft-sale-widget/commons/skeleton-card.tsx
components/nft-sale-widget/layout/owned-nfts/owned-nfts.tsx
components/nft-sale-widget/psyc-item.tsx

- skeleton loader for owned nfts section
- skeleton for nft price

feat: skeleton loaders for owned section

---

components/nft-sale-widget/hooks/useMintSection.ts
components/nft-sale-widget/layout/nft-sale/mint-section.tsx
components/nft-sale-widget/psyc-item.tsx
hooks/useImageData.tsx

introduced a fallback to prevent Batches from breaking due to missing imageUris

fix missing imageUri

---

components/nft-sale-widget/hooks/useMintSection.ts
components/nft-sale-widget/layout/nft-sale/mint-section.tsx
components/nft-sale-widget/psyc-item.tsx

- created a useMintSection hook for encapsulating logic related to managing the mint section
- refactored the `MintSection` component and introduced new subcomponents `RandomPsycItem` and `SpecificPsycItems`
- Moved the `refetchBalances` prop in the `PsycItem` component to ensure it's consistently applied.
- Improved import organization for multiple files.
ToDO - Refactor PsycItem component to have `usePsycItem` hook and introduction of subcomponents

WIP: refactor mint section component

---

components/nft-sale-widget/index.tsx
components/nft-sale-widget/layout/nft-sale/mint-psyc-header.tsx
components/nft-sale-widget/layout/owned-nfts/owned-nft-item.tsx
components/nft-sale-widget/layout/owned-nfts/owned-nfts.tsx

fix: increase size of bottom margin to prevent cut off
made some adjustments to prevent cut-off of owned NFT display on initial load

fix: improve add nft button appearance

---

components/nft-sale-widget/hooks/usePsycItem.ts
components/nft-sale-widget/layout/nft-sale/mint-section.tsx
components/nft-sale-widget/psyc-item.tsx
hooks/useReadTokenInformation.ts

- Created the `usePsycItem` hook to encapsulate the complex logic
- Removed direct state management and calculation logic from the component.
- Updated the component to use the states and functions provided by `usePsycItem`.
- Improved conditional rendering logic for better readability.
- Extracted smaller, reusable components for overlays and price displays.
- Removed redundant `isAddressesLoading` as a _prop_ from `MintSection `

Refactor PsycItem Component and Introduce usePsycItem Hook

---

components/claim/claim-card.tsx
components/claim/dummyData.ts
components/ui/menu.tsx
components/windows/claim.tsx
lib/types.ts
pages/index.tsx

closes [ticket #111](https://github.com/LinumLabs/PsyDao-FE/issues/112) for initial claim window

Initial claim window

---

components/claim/create-reward-claim.tsx
hooks/useGetAvailableAllowance.tsx
services/web3/useApprovePsy.tsx

- Added success and error toasts to approve flow
- Made it so that if the user doesn't have an allowance of enough tokens then only the approve button is visible, otherwise create button is visible
- Added refetch after approve

Feat: update approval flow

---

config/apolloClients.ts
config/graphql.ts
config/graphqlClients.ts
hooks/useBuyNft.ts
lib/services/psydaoSubgraph.ts
lib/services/snapshotGraphQL.ts
pages/_app.tsx
pages/index.tsx

accidentally merged my feature branch feat/eb/move-clients into my other feature branch (no base branch auto-update), not feat-am-backend-functions. This merges those same changes into feat-am-backend-functions

move clients around

---

.eslintrc.json

- removed the `.eslintrc.json` I added as it the newer flat config system file is already there and this causes a conflict when building

fix:remove .eslintrc.json

---

components/claim/claim-card.tsx
hooks/useCustomToasts.ts
lib/services/getPsycHolders.ts
lib/services/getPsycHoldersNoProposals.ts
lib/services/merkle.ts
lib/services/voteCounter.test.ts
lib/services/voteCounter.ts
services/graph.ts

We can now add claims where there were no proposals, so basically the tokens are split amongst NFT (PsyC) token holders that exist in that time period

feat: ability to add claims without proposals
